import { Tour } from "./types";

export const mockTours: Tour[] = [
  {
    _id: "1",
    title: "Tham quan Lung Cu - Ha Giang voi canh dep tuyet tran",
    destination: "Lung Cu - Ha Giang",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "2",
    title: "Khám phá vẻ đẹp thiên nhiên tại Mù Cang Chải",
    destination: "Mù Cang Chải",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "3",
    title: "Trải nghiệm văn hóa bản địa ở Sapa",
    destination: "Sapa",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "4",
    title: "Chinh phục đỉnh Fansipan - nóc nhà Đông Dương",
    destination: "Fansipan",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "5",
    title: "Dạo chơi giữa hàng cây phong đỏ ở Hà Nội vào mùa thu",
    destination: "Hà Nội",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "6",
    title: "Thưởng thức ẩm thực miền Trung tại Đà Nẵng",
    destination: "Đà Nẵng",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "7",
    title: "Khám phá di tích lịch sử tại Hội An",
    destination: "Hội An",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "8",
    title: "Ngắm hoàng hôn trên biển Nha Trang",
    destination: "Nha Trang",
    description: "",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
  {
    _id: "9",
    title: "Ha Giang Loop and Dong Van Kast Plateau Amazing 2 Days Car Tour",
    destination: "Ha Giang",
    description: "Explore the rural wonders of Cao Bang and Ha Giang. Explore the most famous places in the North...",
    photo: ["/placeholder.svg?height=200&width=300"],
    overalReview: 4.5,
  },
]